# Utiliser une image de base Python
FROM python:3.11-slim

# Installer les outils de compilation, Tkinter et Nmap
RUN apt-get update && apt-get install -y \
    gcc \
    libc-dev \
    tk-dev \
    tcl-dev \
    nmap \
    && rm -rf /var/lib/apt/lists/*

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le fichier requirements.txt dans le conteneur
COPY requirements.txt .

# Installer les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Copier tout le code de l'application dans le conteneur
COPY . .

# Commande à exécuter lorsque le conteneur démarre
CMD ["python", "main.py"]