version: '3.11'

services:
  harvester:
    build: .
    container_name: seahawks_harvester
    environment:
      - DISPLAY=host.docker.internal:0.0  
    volumes:
      - .:/app
    ports:
      - "5000:5000"