name: Build and Release Harvester

on:
  push:
    branches:
      - harvester
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger le code
        uses: actions/checkout@v3

      - name: Créer un zip
        run: |
          mkdir dist
          zip -r dist/harvester.zip . -x "*.git*" ".github/*"

      - name: Créer une release GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.${{ github.run_number }}
          name: Version v1.${{ github.run_number }}
          files: dist/harvester.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
