name: CI for Seahawks Harvester

on:
  push:
    branches:
      - harvester
  pull_request:
    branches:
      - harvester

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Assurez-vous d'utiliser une version compatible

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installe toutes les dépendances

      - name: Run tests
        run: |
          echo "Aucun test n'est spécifié."  # Remplacez ceci par vos tests si nécessaire

      - name: Deploy Harvester
        run: |
          echo "Déploiement de l'application Harvester"
