  name: Python Package

on:
  push:
    branches:
      - main  # 

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v2

      - name: Installer Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r harvester/requirements.txt

      - name: Exécuter le script
        run: |
          python harvester/main.py  
